name: mena
description: Mena platform

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependency_overrides:
  camera_android: ^0.10.8+13
  intl: ^0.18.0
dependencies:
  add_2_calendar: ^3.0.1
  audio_session: ^0.1.13
  audio_video_progress_bar: ^2.0.1
  bloc: ^8.1.0
  cached_network_image: ^3.2.1
  camera: ^0.10.5+5
  carousel_slider: ^4.1.1
  cloud_firestore: ^4.3.1
  connectivity_plus: ^5.0.1
  cupertino_icons: ^1.0.2
  custom_marker: ^1.0.0
  dartz: ^0.10.1
  dio: ^5.2.0
  dotted_border: ^2.0.0+1
  dropdown_button2: ^2.1.2
  easy_image_viewer: ^1.2.0
  equatable: ^2.0.5
  extended_text: ^11.1.0
  figma_squircle: ^0.5.3
  file_picker: ^5.2.5
  firebase_core: ^2.4.1
  flick_video_player: ^0.5.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_cache_manager: ^3.3.0
  flutter_cupertino_date_picker_fork: 1.0.7
  flutter_datetime_picker_plus: ^2.1.0
  flutter_holo_date_picker: ^1.1.3
  flutter_html: null
  flutter_launcher_icons: ^0.11.0
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.0
  flutter_slidable: ^3.0.1
  flutter_sound: ^9.2.13
  flutter_staggered_grid_view: ^0.7.0
  flutter_summernote: ^1.1.1
  flutter_svg: ^1.0.1
  flutter_switch: ^0.3.2
  flutter_webrtc: ^0.9.34
  fluttertoast: ^8.2.2
  geolocator: ^9.0.2
  get_it: ^7.6.4
  get: null
  google_maps_flutter: ^2.2.1
  google_maps_place_picker_mb: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # html_editor_enhanced: ^2.5.1
  http: ^0.13.5
  image_picker: ^0.8.6
  intl: ^0.18.1
  intl_phone_number_input: ^0.7.0+2
  json_store: ^2.0.0
  just_audio: ^0.9.31
  keyboard_emoji_picker: ^1.0.1
  like_button: ^2.0.5
  lottie: ^2.2.0
  m_toast: ^0.2.4
  map_launcher: ^3.0.1
  multi_select_flutter: ^4.1.2
  outline_gradient_button: ^2.0.1+1
  pull_down_button: ^0.1.0-beta.6
  package_info_plus: ^3.1.2
  page_transition: ^2.0.9
  path_provider: ^2.0.11
  permission_handler: ^11.0.1
  persistent_bottom_nav_bar_v2: ^4.2.4
  pin_code_fields: ^8.0.1
  preload_page_view: ^0.2.0
  pull_to_refresh: ^2.0.0
  quill_html_editor: null
  screen_recorder: ^0.2.0
  scrollable_positioned_list: ^0.3.5
  share_plus: ^6.0.0
  shared_preferences: ^2.0.15
  socket_io_client: ^2.0.3+1
  spinner_date_time_picker: ^0.0.8
  sqflite: ^2.1.0
  staggered_grid_view_flutter: ^0.0.4
  syncfusion_flutter_pdfviewer: ^21.1.38
  table_calendar: ^3.0.9
  transparent_image: ^2.0.0
  url_launcher: ^6.1.10
  video_player: ^2.4.7
  visibility_detector: ^0.3.3
  # webview_flutter: ^4.2.2
  whiteboard: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_launcher_icons: "^0.10.0"
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/mena.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  #generators
  hive_generator: null
  build_runner: null

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/allNewDesign/
    - assets/menamarket/
    - assets/images/
    - assets/icons/
    - assets/icons/messenger/
    - assets/images/public/
    - assets/svg/
    - assets/json/
    - assets/svg/icons/
    - assets/svg/meetings/
    - assets/svg/icons/profile/
    - assets/flags/
    - assets/video/
    - assets/new_icons/
    - assets/fonts/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf

    - family: Visby
      fonts:
        - asset: assets/fonts/visby-cufonfonts/VisbyLight.otf

    - family: VisbyBold
      fonts:
        - asset: assets/fonts/visby-cufonfonts/VisbyBold.otf

    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf

    - family: RobotoBold
      fonts:
        - asset: assets/fonts/roboto/Roboto-Bold.ttf

    - family: Crimson
      fonts:
        - asset: assets/fonts/crimson/CrimsonPro-VariableFont_wght.ttf

    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Regular.ttf

    - family: LatoBold
      fonts:
        - asset: assets/fonts/lato/Lato-Bold.ttf

    - family: PNfont
      fonts:
        - asset: assets/fonts/PN-Font.otf

    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/open_sans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/open_sans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/open_sans/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/open_sans/OpenSans-Light.ttf
          weight: 200
